const villagerImages = {
    "Abigail": require('./Abigail.png'), 
    "Alex": require('./Alex.png'), 
    "Caroline": require('./Caroline.png'), 
    "Clint": require('./Clint.png'), 
    "Demetrius": require('./Demetrius.png'), 
    "Dwarf": require('./Dwarf.png'), 
    "Elliott": require('./Elliott.png'), 
    "Emily": require('./Emily.png'), 
    "Evelyn": require('./Evelyn.png'), 
    "George": require('./George.png'), 
    "Gus": require('./Gus.png'), 
    "Haley": require('./Haley.png'), 
    "Harvey": require('./Harvey.png'), 
    "Jas": require('./Jas.png'), 
    "Jodi": require('./Jodi.png'), 
    "Junimo": require('./Junimo.png'),
    "Kent": require('./Kent.png'), 
    "Krobus": require('./Krobus.png'), 
    "Leah": require('./Leah.png'),
    "Leo": require('./Leo.png'), 
    "Lewis": require('./Lewis.png'), 
    "Linus": require('./Linus.png'), 
    "Marnie": require('./Marnie.png'), 
    "Maru": require('./Maru.png'), 
    "Pam": require('./Pam.png'), 
    "Penny": require('./Penny.png'), 
    "Pierre": require('./Pierre.png'), 
    "Robin": require('./Robin.png'), 
    "Sam": require('./Sam.png'), 
    "Sandy": require('./Sandy.png'), 
    "Sebastian": require('./Sebastian.png'), 
    "Shane": require('./Shane.png'), 
    "Vincent": require('./Vincent.png'), 
    "Willy": require('./Willy.png'), 
    "Wizard": require('./Wizard.png'),
    "Universal": require('./Universal.png')
}

export default villagerImages;